### ISSUE TITLE
输出错误的数字

### ISSUE THREAD

**Issue by janzxgit** [Ailln/en2an#3]
**Describe the bug**
import en2an
output = en2an.an2en("210000", "up")
output
'TEN THOUSAND'
我试了其他数字，都没有问题，就是这个'210000'会返回错误的数字。
我的环境是mac下的anaconda的jupyterBook，python3.8

**Comment by Ailln** [comment]
经过测试，这确实是个 BUG，感谢反馈～

修复版本 `v0.0.7` 已经提交，请更新！

**Comment by janzxgit** [comment]
深谢您的辛苦工作！

**Comment by Ailln** [comment]
不客气～
